name: PositionalDiscord
main: me.tgwaffles.positionaldiscord.PositionalDiscord
version: 1.0
api-version: "1.15"

commands:
  radio:
    description: Join a radio channel.
    usage: /radio <channel id/lock/list>

  volume:
    description: Change a user's volume.
    usage: /volume <user> <volume>

  register:
    description: Register your account to discord. Only use this when prompted to.
    usage: /register <code>

  deregister:
    description: Unlink your Minecraft account from your Discord account.
    usage: /deregister
